; Tests OR with more than 2 arguments
; COME BACK LATER AND FIX THIS ONE
; COME BACK LATER AND FIX THIS ONE
; COME BACK LATER AND FIX THIS ONE
; COME BACK LATER AND FIX THIS ONE
; COME BACK LATER AND FIX THIS ONE
; COME BACK LATER AND FIX THIS ONE
; COME BACK LATER AND FIX THIS ONE

(define (main)
  (display 'hi)
  )
